// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Hotel_Manager.FRONTEND_RESERVATIONModels;

public partial class FRONTEND_RESERVATIONContext : DbContext
{
    public FRONTEND_RESERVATIONContext(DbContextOptions<FRONTEND_RESERVATIONContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Reservation> Reservations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Reservation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC070939E04D");

            entity.ToTable("reservation");

            entity.Property(e => e.AptSuite)
                .HasMaxLength(50)
                .HasColumnName("apt_suite");
            entity.Property(e => e.ArrivalTime)
                .HasColumnType("date")
                .HasColumnName("arrival_time");
            entity.Property(e => e.BirthDay)
                .HasMaxLength(50)
                .HasColumnName("birth_day");
            entity.Property(e => e.BreakFast).HasColumnName("break_fast");
            entity.Property(e => e.CardCvc)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("card_cvc");
            entity.Property(e => e.CardExp)
                .HasMaxLength(50)
                .HasColumnName("card_exp");
            entity.Property(e => e.CardNumber)
                .HasMaxLength(50)
                .HasColumnName("card_number");
            entity.Property(e => e.CardType)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("card_type");
            entity.Property(e => e.CheckIn).HasColumnName("check_in");
            entity.Property(e => e.City).HasColumnName("city");
            entity.Property(e => e.Cleaning).HasColumnName("cleaning");
            entity.Property(e => e.Dinner).HasColumnName("dinner");
            entity.Property(e => e.EmailAddress).HasColumnName("email_address");
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .HasColumnName("first_name");
            entity.Property(e => e.FoodBill).HasColumnName("food_bill");
            entity.Property(e => e.Gender)
                .HasMaxLength(50)
                .HasColumnName("gender");
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .HasColumnName("last_name");
            entity.Property(e => e.LeavingTime)
                .HasColumnType("date")
                .HasColumnName("leaving_time");
            entity.Property(e => e.Lunch).HasColumnName("lunch");
            entity.Property(e => e.NumberGuest).HasColumnName("number_guest");
            entity.Property(e => e.PaymentType)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("payment_type");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .HasColumnName("phone_number");
            entity.Property(e => e.RoomFloor)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("room_floor");
            entity.Property(e => e.RoomNumber)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("room_number");
            entity.Property(e => e.RoomType)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("room_type");
            entity.Property(e => e.SSurprise).HasColumnName("s_surprise");
            entity.Property(e => e.State)
                .HasMaxLength(50)
                .HasColumnName("state");
            entity.Property(e => e.StreetAddress).HasColumnName("street_address");
            entity.Property(e => e.SupplyStatus).HasColumnName("supply_status");
            entity.Property(e => e.TotalBill).HasColumnName("total_bill");
            entity.Property(e => e.Towel).HasColumnName("towel");
            entity.Property(e => e.ZipCode)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("zip_code");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}