// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Hotel_Manager.FRONTEND_RESERVATIONModels;

public partial class Reservation
{
    public int Id { get; set; }

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string BirthDay { get; set; } = null!;

    public string Gender { get; set; } = null!;

    public string PhoneNumber { get; set; } = null!;

    public string EmailAddress { get; set; } = null!;

    public int NumberGuest { get; set; }

    public string StreetAddress { get; set; } = null!;

    public string AptSuite { get; set; } = null!;

    public string City { get; set; } = null!;

    public string State { get; set; } = null!;

    public string ZipCode { get; set; } = null!;

    public string RoomType { get; set; } = null!;

    public string RoomFloor { get; set; } = null!;

    public string RoomNumber { get; set; } = null!;

    public double TotalBill { get; set; }

    public string PaymentType { get; set; } = null!;

    public string CardType { get; set; } = null!;

    public string CardNumber { get; set; } = null!;

    public string CardExp { get; set; } = null!;

    public string CardCvc { get; set; } = null!;

    public DateTime ArrivalTime { get; set; }

    public DateTime LeavingTime { get; set; }

    public bool CheckIn { get; set; }

    public int BreakFast { get; set; }

    public int Lunch { get; set; }

    public int Dinner { get; set; }

    public bool Cleaning { get; set; }

    public bool Towel { get; set; }

    public bool SSurprise { get; set; }

    public bool SupplyStatus { get; set; }

    public int FoodBill { get; set; }
}