// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Hotel_Manager.LOGIN_MANAGERModels;

public partial class Frontend
{
    public string UserName { get; set; } = null!;

    public string PassWord { get; set; } = null!;
}