// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Hotel_Manager.LOGIN_MANAGERModels;

public partial class LOGIN_MANAGERContext : DbContext
{
    public LOGIN_MANAGERContext(DbContextOptions<LOGIN_MANAGERContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Frontend> Frontends { get; set; }

    public virtual DbSet<Kitchen> Kitchens { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Frontend>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK_Table");

            entity.ToTable("frontend");

            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .HasColumnName("user_name");
            entity.Property(e => e.PassWord)
                .HasMaxLength(50)
                .HasColumnName("pass_word");
        });

        modelBuilder.Entity<Kitchen>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK__kitchen__7628B51D2FDAF8B5");

            entity.ToTable("kitchen");

            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .HasColumnName("user_name");
            entity.Property(e => e.PassWord)
                .HasMaxLength(50)
                .HasColumnName("pass_word");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}